version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
        - "8080:80"
    volumes:
        - ./app:/var/www/project
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php8
  php8:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php8-container
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/project