version: '3'

services:
  nginx:
    image: nginx:stable-alpine # 1.24.0
    container_name: nginx-container
    ports:
        - "8080:80"
    volumes:
        - ./:/var/www/project
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php8
  php8:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php8-container
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/project
