<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8b2jax3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8b2jax3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8b2jax3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8b2jax3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8b2jax3\App_KernelDevDebugContainer([
    'container.build_hash' => '8b2jax3',
    'container.build_id' => 'fa83c93e',
    'container.build_time' => 1708378899,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8b2jax3');
